# Colores oscuros
COLOR_DE_FONDO_DARK = "#580c49"
COLOR_DE_TEXTO_DARK = "white"
COLOR_BOTONES_ESPECIALES_DARK = "#d7a3ca"
COLOR_BOTONES_DARK = "#640909"
COLOR_CAJA_TEXTO_DARK = "#EB094D"

# Colores claros
COLOR_DE_FONDO_LIGHT = "#B46A93"
COLOR_DE_TEXTO_LIGHT = "black"
COLOR_BOTONES_ESPECIALES_LIGHT = "#B165B4"
COLOR_BOTONES_LIGHT = "#448d5b"
COLOR_CAJA_TEXTO_LIGHT = "#ffffff"